// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz4u2PwRmsd-DfjibSknFv4sxTWLw0UAA',
    appId: '1:606361293156:web:e0815e3ffd82a50d0e6a71',
    messagingSenderId: '606361293156',
    projectId: 'fir-8cd9d',
    authDomain: 'fir-8cd9d.firebaseapp.com',
    storageBucket: 'fir-8cd9d.appspot.com',
    measurementId: 'G-TC5FYH6FDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgA7CanlZzsRHvO2z3ccJsk85o5nHmt_o',
    appId: '1:606361293156:android:1c116f5500265ea00e6a71',
    messagingSenderId: '606361293156',
    projectId: 'fir-8cd9d',
    storageBucket: 'fir-8cd9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0svxOS9wxkz-Bs_lRVMi2qjB6UCA1dk8',
    appId: '1:606361293156:ios:6fd87cd13c4746490e6a71',
    messagingSenderId: '606361293156',
    projectId: 'fir-8cd9d',
    storageBucket: 'fir-8cd9d.appspot.com',
    iosBundleId: 'net.magah.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0svxOS9wxkz-Bs_lRVMi2qjB6UCA1dk8',
    appId: '1:606361293156:ios:6fd87cd13c4746490e6a71',
    messagingSenderId: '606361293156',
    projectId: 'fir-8cd9d',
    storageBucket: 'fir-8cd9d.appspot.com',
    iosBundleId: 'net.magah.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz4u2PwRmsd-DfjibSknFv4sxTWLw0UAA',
    appId: '1:606361293156:web:b541fed435d1cf6b0e6a71',
    messagingSenderId: '606361293156',
    projectId: 'fir-8cd9d',
    authDomain: 'fir-8cd9d.firebaseapp.com',
    storageBucket: 'fir-8cd9d.appspot.com',
    measurementId: 'G-9N9E9M2LCB',
  );

}